project:
  type: website
  output-dir: docs

website:
  title: "Aghata Charnobay"
  favicon: images/AC_favicon.png
  navbar:
    logo: images/AC_logo_bars.png
    right:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
        
        
  page-footer:
    background: light
    border: true
    left:  Â© 2026 Aghata Charnobay
    center: 
    - icon: linkedin
      href: https://www.linkedin.com/in/aghata-charnobay/
      target: _blank
    - icon: github
      href: https://github.com/a-charnobay
      target: _blank
    - icon: envelope
      href: mailto:aghatacharnobay@gmail.com
      target: _blank
    right: Made with [Quarto](https://quarto.org/){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}, and ðŸ–¤

format:
  html:
    theme: [theme.scss]
    toc: true
    toc-depth: 3
    page-layout: article
    smooth-scroll: true
    
comments:
  giscus:
    repo: a-charnobay/a-charnobay.github.io

editor: visual

